<?php
	$_user = $this->getCurrentUser();
	if($_user->getGoogleOauthEnabled()){
?>
<div class="content-header">
	<h3 class="icon-head head-system-account"><?php echo $this->__("Validate authentication code"); ?></h3>
</div>
<div class="entry-edit">
	<form action="<?php echo $this->getFormAction(); ?>" method="post" id="validate_form">
		<input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>">
		<input name="account" type="hidden" value="1">
		<div class="entry-edit-head">
			<h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__("Check your code"); ?></h4>
		</div>
		<div class="fieldset" id="validator_fieldset">
			<div class="hor-scroll">
				<table cellspacing="0" class="form-list">
					<tbody>
					<tr>
						<td class="label"><label for="code"><?php echo $this->__("Insert your code"); ?> <span class="required">*</span></label></td>
						<td class="value">
							<input id="code" name="code" title="<?php echo $this->__("Insert your code"); ?>" type="text" class="input-text required-entry">
						</td>
						<td class="action" style="vertical-align: middle;">
							<button type="submit" class="scalable success" style="margin-left: 20px;">
								<span>
									<span><?php echo $this->__("Validate"); ?></span>
								</span>
							</button>
						</td>
					</tr>
					</tbody>
				</table>
			</div>
		</div>
	</form>
	<script type="text/javascript">
		let form = new varienForm('validate_form', '');
	</script>
</div>
<?php } ?>