<?php
	$_secretInfo = $this->getSecretInfo();
?>
<div class="page-title">
	<h1><?php echo $this->__('Mange your two factor authentication') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->toHtml() ?>
<form action="<?php echo $this->getUrl('google_oauth/index/save'); ?>" method="post" id="form-validate" autocomplete="off">
	<div class="fieldset">
		<h2 class="legend"><?php echo $this->__('Settings') ?></h2>
		<ul class="form-list">
			<li class="col2-set">
				<div class="col-1">
					<label for="enabled" class="required"><em>*</em><?php echo $this->__('Two factor authentication enabled') ?></label>
					<div class="input-box">
						<select name="enabled" id="enabled" class="validate-select required-entry">
							<option value="0" <?php echo !$_secretInfo->getEnabled() ? 'selected' : ''; ?>><?php echo $this->__("No"); ?></option>
							<option value="1" <?php echo $_secretInfo->getEnabled() ? 'selected' : ''; ?>><?php echo $this->__("Yes"); ?></option>
						</select>
					</div>
				</div>
				<div class="col-2">
					<?php if($_secretInfo->getEnabled()){ ?>
						<label for="secret"><?php echo $this->__('QR Code') ?></label>
						<img id="secret" src="<?php echo $_secretInfo->getQrCode(); ?>">
						<br>
						<ul class="messages">
							<li class="success-msg">
								<ul>
									<li><?php echo $this->__("Scan this code with your 'Authenticator' app for enable code in your device"); ?></li>
								</ul>
							</li>
						</ul>
					<?php }else{ ?>
						<ul class="messages">
							<li class="notice-msg">
								<ul>
									<li><?php echo $this->__("Enable this option to scan QR code to start two factor authentication."); ?></li>
								</ul>
							</li>
						</ul>
					<?php } ?>
				</div>
			</li>
			<div class="buttons-set">
				<button type="submit" class="button"><span><span><?php echo $this->__("Save"); ?></span></span></button>
			</div>
		</ul>
	</div>
</form>
<?php if($_secretInfo->getEnabled()){ ?>
<form action="<?php echo $this->getUrl('google_oauth/index/validate'); ?>" method="post" id="test-form-validate" autocomplete="off">
	<input type="hidden" name="account" value="1">
	<div class="fieldset">
		<h2 class="legend"><?php echo $this->__('Verify your code') ?></h2>
		<ul class="form-list">
			<li class="col2-set">
				<div class="col-1">
					<label for="code" class="required"><em>*</em><?php echo $this->__('Code') ?></label>
					<div class="input-box">
						<input type="text" name="code" id="code" class="input-box required-entry" placeholder="<?php echo $this->__("Insert 'Authenticator' app code"); ?>">
					</div>
				</div>
				<div class="col-2">
					<br>
					<button type="submit" class="button width-full"><span><span><?php echo $this->__("Validate"); ?></span></span></button>
				</div>
			</li>
		</ul>
	</div>
</form>
<?php } ?>
<script type="text/javascript">
	let form		 	= new VarienForm('form-validate');
	let formValidator	= new VarienForm('test-form-validate');
</script>